version: "2"

services:
  www:
    image: wordpress
    container_name: www
    volumes:
      - ./src:/var/www/html
      - ./src/log:/var/log/apache2
    working_dir: /var/www/html
    links:
      - mysql:mysql
    ports:
      - 8888:80
    environment:
      - ALLOW_OVERRIDE=true
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=spz@123451
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spz@123451
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./stack/mysql/data:/var/lib/mysql
      - ./stack/mysql/entrypoint:/docker-entrypoint-initdb.d

  devtools:
      image: rualatngua/devtools:2.0
      container_name: devtools
      links:
        - mysql:mysql
      ports:
        - 8889:80
      environment:
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=spz@123451
      depends_on:
        - mysql